### ISSUE TITLE
Evaluation Form

### ISSUE THREAD

**Issue by FinjaBaeumcher** [FinjaBaeumcher/Capstone-Project#15]
## Value Proposition

As a user I want to rate my Yoga session 
so that I can compare my daily well-being before and after a yoga session
​

## Description
​
![Bildschirm­foto 2023-03-27 um 13 11 54](https://user-images.githubusercontent.com/123068226/227925903-4f8ab828-ef47-40fe-8e49-d565172c9464.jpeg)

## Acceptance Criteria

- [ ] There is a descriptive question as a heading 
- [ ] A rating for your mental health is visible
- [ ] A rating for your physical condition is visible
- [ ] There is an input field where you could add a number
- [ ] An input field for comments is visible
- [ ] a rating for your flow is visible
- [ ] the stars of the rating are filled if they are clicked​

## Tasks

- [ ] Add descriptive texts
- [ ] add Smiley-Buttons
- [ ] add input fields
- [ ] add star-rating-buttons
      ​

## Complexity

XL

**Comment by reyk-zepper** [comment]
very detailed, very good...nice to read!
...one suggestion...you can give the pages names in the tasks, so that a dev who isn"t you know how you want to have them named. it can also help make the tasks more readable...
but all in all....very nice work!
