### ISSUE TITLE
Extended Evaluation Form

### ISSUE THREAD

**Issue by FinjaBaeumcher** [FinjaBaeumcher/Capstone-Project#20]
## Value Proposition

As a user I also want to save the time I did yoga
so that I can compare it with other days
​

## Description

![Bildschirm­foto 2023-03-27 um 13 11 54](https://user-images.githubusercontent.com/123068226/228948966-f7b48e1f-5ad4-4e92-81f2-b9561d445ff8.jpeg)
​

## Acceptance Criteria

- [ ] There is a descriptive text
- [ ] An input field is displayed
- [ ] you can click on the input field and type a number in it 
- [ ] the input of the field appears in the progress list
      ​

## Tasks

- [ ] build an input field component
- [ ] add the component to the evaluation form page
- [ ] save the input in the progress list with localStorage, too
      ​

## Complexity

M
