### ISSUE TITLE
Editing Function

### ISSUE THREAD

**Issue by FinjaBaeumcher** [FinjaBaeumcher/Capstone-Project#22]
## Value Proposition

As a user I want an editing function
so that I can change my entries again afterwards
​

## Description

![Bildschirm­foto 2023-03-31 um 14 24 47](https://user-images.githubusercontent.com/123068226/229119492-f98892f8-d47f-4a5d-b1c3-de038aee20ef.jpeg)
​
## Acceptance Criteria

- [ ] There is a button (e.g with a pencil on it)
- [ ] if you click it you could change your entries   ​

## Tasks

- [ ] ​add an update function with help of useState and useEffect

## Complexity

M
