### ISSUE TITLE
Delete Function

### ISSUE THREAD

**Issue by FinjaBaeumcher** [FinjaBaeumcher/Capstone-Project#29]
## Value Proposition

As a user I want to delete unnecessary entrys
so that I can organize my own progress
​

## Description

![Bildschirm­foto 2023-04-11 um 14 46 35](https://user-images.githubusercontent.com/123068226/231166932-3e41f385-23ea-4293-a4b2-17d768291b68.jpeg)

## Acceptance Criteria

- [ ] you can delete individual entries​

## Tasks

- [ ] add a handleDelete function
- [ ] add a delete button​

## Complexity

XS

**Comment by nikokreissl** [comment]
Great work! 🙂
However, I would write the acceptance criteria slightly more detailed
Following information are useful to know for the person doing QA:
- where has the user the option to delete the entry?
- which button needs to be clicked? 
- what happens after click? (user is directed to another page? Is he asked first if he is sure about deleting the entry?
Would be great if you can add such information to the acceptance criteria 🙂
